before:
  hooks:
    - go generate ./cmd

builds:
  - main: ./cmd/pebble
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - "-trimpath"

archives:
  - format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - src: COPYING
        dst: ./COPYING
      - src: README.md
        dst: ./README.md
    rlcp: true  # See https://goreleaser.com/deprecations/#archivesrlcp

snapshot:
  name_template: '{{ if ne .Version "0.0.0" }}{{ .Version }}{{ else }}{{ .ShortCommit }}-devel{{ end }}'
