name: Release

on:
  push:
    tags:
      - v*

jobs:
  binaries:
    name: GoReleaser release
    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.20.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run GoReleaser
        run: |
          pwd
          cat .goreleaser.yaml
          goreleaser release --clean --debug

      - name: Upload binaries
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/*_checksums.txt
            dist/*.tar.gz
