name: Release

on:
  push:
    tags:
      - v*

jobs:
  binaries:
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v3

    - name: Build binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: "0"
      run: |
        go generate ./cmd

        rm -rf dist/build
        go build -trimpath -ldflags='-s -w' -o dist/build/pebble ./cmd/pebble
        cp COPYING dist/build
        cp README.md dist/build

        export PEBBLE_VERSION=$(go run ./cmd/pebble version | awk '/client/ { print $2 }')
        export ARCHIVE_FILE=pebble_${PEBBLE_VERSION}_${GOOS}_${GOARCH}.tar.gz
        tar -czf dist/$ARCHIVE_FILE -C dist/build .

    - name: Upload archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload v$PEBBLE_VERSION dist/$ARCHIVE_FILE
