name: Release

on:
  push:
    tags:
      - v*

jobs:
  binaries:
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3

    - name: Build and upload binary
      env:
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}
        CGO_ENABLED: "0"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo Generating version file
        go generate ./cmd

        echo Building for $GOOS $GOARCH
        rm -rf dist/build
        go build -trimpath -ldflags='-s -w' -o dist/build/pebble ./cmd/pebble

        cp COPYING dist/build
        cp README.md dist/build
        PEBBLE_VERSION=$(go run ./cmd/pebble version | awk '/client/ { print $2 }')
        ARCHIVE_FILE=pebble_${PEBBLE_VERSION}_${GOOS}_${GOARCH}.tar.gz
        echo Creating archive $ARCHIVE_FILE
        tar -czf dist/$ARCHIVE_FILE -C dist/build .

        echo Uploading $ARCHIVE_FILE to relase v$PEBBLE_VERSION
        gh release upload v$PEBBLE_VERSION dist/$ARCHIVE_FILE
